services:
  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    command: ['-config.file=/etc/tempo.yaml']
    volumes:
      - ../observability/tempo.yml:/etc/tempo.yaml
    ports:
      - '3200:3200' # Tempo HTTP API
    healthcheck:
      test: ['CMD', 'wget', '-q', '-O-', 'http://localhost:3200/status']
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    command: ['run', '/etc/alloy/config.alloy']
    volumes:
      - ../observability/alloy.config:/etc/alloy/config.alloy
    ports:
      - '4317:4317' # OTLP gRPC receiver
      - '4318:4318' # OTLP HTTP receiver
    depends_on:
      tempo:
        condition: service_healthy

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000' # Grafana HTTP API
    restart: always
