export const ERROR_CODES = {
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_INPUT: 'INVALID_INPUT',
  REQUIRE_REQUEST_BODY: 'REQUIRE_REQUEST_BODY',
  QUIZ_NOT_FOUND: 'QUIZ_NOT_FOUND',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_NOT_JOINABLE: 'SESSION_NOT_JOINABLE',
  SESSION_NOT_STARTABLE: 'SESSION_NOT_STARTABLE',
  PARTICIPANT_NICKNAME_TAKEN: 'PARTICIPANT_NICKNAME_TAKEN',
  QUESTION_NOT_FOUND: 'QUESTION_NOT_FOUND',
  INVALID_ANCHOR: 'INVALID_ANCHOR',
  DUPLICATE_QUESTION_ORDER: 'DUPLICATE_QUESTION_ORDER',
  DUPLICATE_OPTIONS: 'DUPLICATE_OPTIONS',
  INVALID_OPTIONS: 'INVALID_OPTIONS',
  NO_OPTIONS_ALLOWED: 'NO_OPTIONS_ALLOWED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
